version: "3.8"

services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${OGMIOS_VERSION:-v6.1.0}_${CARDANO_NODE_VERSION:-8.7.3}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:${OGMIOS_PORT:-1337}:1337
      - ${CARDANO_NODE_PORT:-3000}:3000
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc

  kupo:
    image: cardanosolutions/kupo:${KUPO_VERSION:-v2.7.2}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:${KUPO_PORT:-1442}:1442
    command: [
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json",
      "--since", "${KUPO_SINCE:-origin}",
      "--match", "${KUPO_MATCH:-*}",
      "--workdir", "/db",
      "--host", "0.0.0.0",
      "--port", "1442"
    ]
    volumes:
      - kupo-db:/db
      - node-ipc:/ipc
      - ./config/cardano-configurations/network/${NETWORK:-mainnet}:/config

  haproxy:
    image: haproxy:2.8.3
    env_file: ./.env
    environment:
      - NETWORK=${NETWORK:-mainnet}
    ports:
      - ${HAPROXY_PORT:-80}:8080
      - ${HAPROXY_SSL_PORT:-443}:8443
    depends_on:
      - cardano-node-ogmios
      - kupo
    shm_size: '2gb'
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
      - /etc/ssl/ssl_key.pem:/ssl_key.pem
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
  kupo-db:
